# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  workflow_call:

jobs:
  tsc:
    name: tsc-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - name: "setup node"
        uses: actions/setup-node@v4.0.0
        with: 
          node-version: 18
      
      - name: "install dependencies"
        run: npm i && cd client && npm i

      - name: tsc
        uses: icrawl/action-tsc@v1
  
  build:
    name: client-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - name: "setup node"
        uses: actions/setup-node@v4.0.0
        with: 
          node-version: 18
      
      - name: "install dependencies"
        run: npm i && cd client && npm i

      - name: "build client"
        run: npm run build-client
      

  test-client:
    name: Test Client Application
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: "checkout repository"
        uses: actions/checkout@v4.1.1

      - name: "setup node"
        uses: actions/setup-node@v4.0.0
        with: 
          node-version: 18

      - name: "install npm@latest"
        run: npm i -g npm@latest

      - name: "install dependencies"
        run: npm i && cd client && npm i

      - name: "run tests"
        run: npm run test-client --passWithNoTests
  
  test-app:
    name: Test Server Application
    runs-on: ubuntu-latest
    container: node:10.18-jessie
    services:
        redis:
          image: redis
          options: >-
            --health-cmd "redis-cli ping"
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4.1.1
      
      - name: Install deps
        run: npm i

      - name: Connect to Redis
        run: node client.js
        env:
            REDIS_HOST: redis
            REDIS_PORT: 6379
    
        

